### ISSUE TITLE
This repo is a copy of github.com/siboehm/lleaves and violates copyright

### ISSUE THREAD

**Issue by siboehm** [VoltaML/volta-trees#2]
This repo is clearly a copy of my repo: https://github.com/siboehm/lleaves, many of the files even still have the same name (eg `lleaves.py`). You should include the original copyright notice, including my name. What you're currently doing is an illegal copyright violation.

That's the legal part. Here comes the moral part :) Why didn't you just send a PR into lleaves to add XGBoost? That would've been much more in the spirit of Open Source! lleaves already has a good amount of users and stars, proper benchmarks, tests, etc,  plus it's packaged for all major platforms. Also it'd be real nice (though not legally required), to give me some credit in the README for literally writing 95% of the code that is in this repo.

**Comment by VoltaML** [comment]
Hi @siboehm. We're sorry we haven't credited you. We do generally add it in the readme. Honest mistake. We released the repo, wanted to finalize the readme. But our focus has shifted entirely to some other work, our xgboost collaborators became busy and we forgot about this work. Not our intention to do any copyright violation. Genuinely sorry. Will add credit immediately. We can also do a PR and merge XGBoost into your repo only. We will retire this one.
